### ISSUE TITLE
Executing a PAL string causes a NullPointerException

### ISSUE THREAD

**Issue by iowaguy** [PM-Master/policy-machine-core#138]
Executing `PAP.fromPAL(...)` on a PAL string causes a `NullPointerException`.

In the file `Expression.java`, the `Expression` class can have two varieties: `Literal` (which is basically a string) or `List` of `Expressions`. The code path from `PAP.fromPAL(...)` generates an `Expression` literal, but later in the dataflow it tries to extract the `List<Expression>`  which is not defined. This returns `null` and results in a `NullPointerException` later on.

The following is the PAL file I'm using. The first line is the one causing the problems.
```
set resource access rights ['permission0', 'permission4'];
create policy class 'department';

create user 'U1' in 'UA7';

create object 'O1' in 'OA7';

create object attribute 'OA1' in 'department';
create object attribute 'OA2' in 'department';
create object attribute 'OA3' in 'OA2';
create object attribute 'OA4' in 'department';
create object attribute 'OA5' in 'department';
create object attribute 'OA6' in 'OA5';
create object attribute 'OA7' in 'OA6';
assign 'OA6' to 'OA4';
assign 'OA7' to 'OA3';
assign 'OA3' to 'OA1';

create user attribute 'UA1' in 'department';
create user attribute 'UA2' in 'department';
create user attribute 'UA3' in 'UA2';
create user attribute 'UA4' in 'department';
create user attribute 'UA5' in 'department';
create user attribute 'UA6' in 'UA5';
create user attribute 'UA7' in 'UA6';
assign 'UA6' to 'UA4';
assign 'UA7' to 'UA3';
assign 'UA3' to 'UA1';

associate 'UA5' and 'OA5' with ['permission0'];
associate 'UA4' and 'OA5' with ['permission0'];
associate 'UA4' and 'OA4' with ['permission4'];
associate 'UA4' and 'OA2' with ['permission4'];
associate 'UA2' and 'OA2' with ['permission0'];
```

Specifically, the exception occurs when executing
```java
pap.fromPAL(new UserContext(SUPER_USER), policyString);
```

**Comment by joshua-roberts** [comment]
@iowaguy My apologies as this is a result of the lacking documentation on PAL syntax, but the `set resource access rights` and `associate` commands don't need the square brackets around the array, it can just be a comma separated list of string literals or string variables. For example,
```
set resource access rights 'permission0', 'permission4';
associate 'UA5' and 'OA5' with 'permission0';
```

The ANTLR syntax defines an expression array but the compiler ensures the values are strings only.

We should however ensure that a NPE doesn't happen here. I'll keep this open until that is fixed.

**Comment by iowaguy** [comment]
Ok, thanks. Given this, you can ignore my pull request!
