### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by fjlopez** [PM-Master/policy-machine-core#150]
I would like to confirm whether this software is developed by the National Institute of Standards and Technology (NIST). If it is, could you please upload or provide details regarding the license under which this NIST software is published here?

**Comment by joshua-roberts** [comment]
Hi @fjlopez yes, this software is developed by NIST. I've added the license to the active dev branch "3.0dev" and will merge when the updates are ready to merge with the master branch. You can view the license here: https://github.com/PM-Master/policy-machine-core/blob/3.0dev/LICENSE.md. I'll keep this issue open until the branch with the license is merged.

**Comment by joshua-roberts** [comment]
license file now in master branch
