### ISSUE TITLE
Deleting a node with children

### ISSUE THREAD

**Issue by Sox094** [PM-Master/policy-machine-core#73]
When deleting a node, should we delete all the children of that node, or should we keep the standalone nodes somewhere in the graph (with the possibility of assigning all the children somewhere else).

```json
{
  "nodes": [
    {
      "name": "child of the deleted node",
      "type": "UA",
      "properties": {},
      "id": 0
    }
  ],
  "assignments": [],
  "associations": []
}
```

For now, all children of the deleted node are still somewhere on the graph but as they are unassigned they are not being displayed.

**Comment by joshua-roberts** [comment]
As discussed in our meeting, we are going to first check that a node being deleted does not have any children. If it does than it is not deleted.  All child nodes must be deassigned from the node to delete.
