### ISSUE TITLE
Default labeling for obligations event schema

### ISSUE THREAD

**Issue by anweiss** [PM-Master/policy-machine-core#75]
According to https://github.com/PM-Master/policy-machine-core/tree/master/src/main/java/gov/nist/csd/pm/pip/obligations, when `label`'s are unspecified for the various object types (e.g. `obligation`, `rule`, etc), a "random value will be used". Should we implement something specific, such as a UUID, rather than throwing an error which is what the `EVRParser` currently does?

**Comment by joshua-roberts** [comment]
This is an error in the docs. The code expects labels and errors out if one is not provided. I will update the docs to reflect this.

**Comment by anweiss** [comment]
Thanks for the clarification. Will close once docs have been updated.
